name: Verify

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘©â€ğŸ’» Check out repo
        uses: actions/checkout@v2

      - name: ğŸ§° Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: â¬‡ï¸ Install deps
        run: yarn install

      - name: ğŸ“— Lint
        run: yarn lint

      - name: ğŸ” Type check
        run: yarn type-check

      - name: âœ” Run tests
        run: yarn test
